### ISSUE TITLE
Hard to translate. Although event handlers appear to be...

### ISSUE THREAD

**Issue by SurenAt93** [reactjs/hy.reactjs.org#13]
Տարբերակներ կառաջարկե՞ք։

Although event handlers appear to be rendered inline, they will be collected and implemented using event delegation.

**Comment by GoharArya** [comment]
Թեպետ թվում է, թե իրադարձություն մշակողները արտապատկերվում են գծայնորեն (գծային կերպով), սակայն (իրականում) նրանք հավաքվում և կիրարկվում են (գործարկվում, կիրառվում)` օգտագործելով իրադարձությունների պատվիրակում (իրադարձությունների պատվիրակման ճանապարհով)։

**Comment by SurenAt93** [comment]
`իրադարձությունների պատվիրակում`-ը միգուցե փոխարինենք `իրադարձությունների փոխանցում`-ո՞վ։

**Comment by nikarm22** [comment]
Թեպետ թվում է, թե իրադարձություն մշակողները միջտողային (inline) են կցված, սակայն իրականում նրանք հավաքվում և իրականացվում են` օգտագործելով իրադարձությունների պատվիրակում (event delegation):
