### ISSUE TITLE
Տերմինաբանություն: Render | Rendering

### ISSUE THREAD

**Issue by tigrankeshishyan** [reactjs/hy.reactjs.org#5]
Շատ կարևոր բառ ունենք տարգմանելու ժող։
Render | Rendering

Այս մեկնաբանությունը կթարմացվի կախված քննարկումներից:

Ներկայիս տարբերակներից են.
- պատկերել
- նկարել
- վերարտադրել
- նյութավորել ([աղբյուր](https://glosbe.com/en/hy/client-side%20rendering))
- Թողնել render
- արտապատկերել ( հակասում է մաթեմատիկական տերմինին )
- [արտանկարել](https://bararanonline.com/%D5%A1%D6%80%D5%BF%D5%A1%D5%B6%D5%AF%D5%A1%D6%80%D5%A5%D5%AC) ( նշանակում է պատճենել, իմաստը չի արտահայտում )

Stay tuned!

**Comment by EdwardStepanian** [comment]
Միգուցե պատկերել ՞

**Comment by adsellor** [comment]
իմ կարծիքով արտապատկերումն/արտանկարումն ավելի լավ են նկարագրում պրոցեսը․

**Comment by SurenAt93** [comment]
@adsellor ջան իմ կարծիքով մաթեմատիկոսներին ( ու ոչ միայն 😄) դուր չի գա `արտապատկերում` բառի կիրառումը, որպես `render` - ի թարգմանություն։ f X -> Y

Կարանք իրա ֆունկցիան, որպես արտապատկերում սահմանենք մի ձեւ, եթե շատ ուզենք, բայց ոչ թարգմանություն։

**Comment by VahanAper** [comment]
render - պատկերել
rendering - պատկերում

**Comment by nikarm22** [comment]
Արտանկարելը - պատճեն ա, render-ի իմաստը կորում ա:

Եվս 2 տարբերակ մտածելու համար.
Render/Rendering - Նյութավորել/Նյութավորում:
Կամ render-ը չթարգմանել:

**Comment by GoharArya** [comment]
«Վերարտադրել»-ը կամ «նյությավորել»֊ն ավելի մոտ են իմաստին։ Չնայած, չթարգմանելը նույնպես տարբերակ է։

**Comment by tigrankeshishyan** [comment]
Իմ կարծիքով 'պատկերել'-ը React-ի դեպքում ավելի լավ ա բնութագրում իրավիճակը։ Իհարկե բուն նկարման պահը կատարվում է React-ի կողմից, բայց ողջ React թիմը իր բոլոր  ելույթներում render-ը կապում է նկարելու, պատկերելու հետ։

**Comment by SurenAt93** [comment]
@nikarm22 - ը սենց մի հատ տարբերակ առաջարկեց. ասում ա, `render` - ը եկեք թարգմանենք `արտապատկերում`, հիմնվելով էն գաղափարի վրա, որ `render` - ը ֆունկցիա է, որը արտապատկերում է Virtual DOM - ը DOM - ում։ Խնդիրը նրանում է, որ ինչպես արդեն [նշել](https://github.com/reactjs/hy.reactjs.org/issues/5#issuecomment-462493094) էի, կարող ենք, `render` - ի ֆունկցիան որպես արտապատկերում սահմանենլ, բայց ոչ `render` - ի թարգմանությունը։ Բոլոր ֆունկցիաններն էլ արտապատկերում էն մի բազմույունից մյուսը։ Այդպիսի ֆունկցի է օրինակ բազմապատկումը, բայց բազմապատկումը (mul) չենք կարող թարգմանել արտապատկերում։

Բայց հետո հայտնաբերեցինք, որ `render` - բառը (ոչ ֆունկցիան) նույնպես օգտագործվում է, որպես արտապատկերում. օրինակ

A translator renders one language into another.
An artist can render an idea in the mind into a drawing on paper.

Մի քանի թարգմանության օրինակ էլ տվյալ կոնտեքստում.

Rendering Elements - Էլեմենտների արտապատկերում
Rendering an Element into the DOM - Էլեմենտնի արտապատկերումը DOM-ում
Updating the Rendered Element - Արտապատկերված էլեմենտի թարմացում։

Այսպիսով, որոշեցինք `render` - ը թարգմանել `արտապատկերում`։

Any ideas?

**Comment by EdwardStepanian** [comment]
`render` - ը ֆունկցիա է, որը արտապատկերում է Virtual DOM - ը DOM - ում։
Ես մտքի հետ համաձայն եմ, բայց կարդացողը անընդհատ մտածելուա դոմի մասին, ու պատճենելու մասին։ Արտա նախածանցը շեղումա `render`ի պատկերելու գաղափարից։
