### ISSUE TITLE
Տերմինաբանություն: Component-Based

### ISSUE THREAD

**Issue by SurenAt93** [reactjs/hy.reactjs.org#6]
Ինչ-որ մտքեր կա՞ն `Component-Based` - ի թարգմանության։

**Comment by Artur93gev** [comment]
Կոմպոնենտով հիմնված

**Comment by nikarm22** [comment]
Կոնկրետ հոմ էջի վերնագիրը կարա լինի ուղղակի «Կոմպոնենտային»

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Artur93gev** [comment]
Im karciqov et 3 vernagrer@ yentadrabar hamapatasxanum en
React is something
Tesqin. Hetevabar karogh enq yerkar el grel

**Comment by SurenAt93** [comment]
Արտ ջան, բայց արի  `component-based` - ը փորձենք կիրառենլ ուրիշ տեղ, օրինակ `component-based architecture` (ու հիմնականում հենց էս նկատի ունեն), էս կթարգմանվի
`կոմպոնենտային ճարտարապետություն`,
ոչ թե `կոմպոնենտով հիմնված ճարտարապետություն`։ 

BTW; ռուսները, թարգմանել են սենց - `Основан на компонентах `։

**Comment by Artur93gev** [comment]
De yes el em et asum основа  հիմք

**Comment by nikarm22** [comment]
Էտ դեպքում կարա, օրինակ, վերնագիրը լինի 'Հիմնված կոմպոնենտների վրա', իսկ մյուս դեպքերում 'Կոմպոնենտային':

**Comment by GoharArya** [comment]
Կարող ենք նաև «կոմպոնենտահեն» տարբերակը դիտարկել ելնելով հայերենի բառակազմության կանոններից։ Ավելի բնական կընդունվի իմ կարծիքով։
